[package]
name = "mimalloc-rust-sys"
description = "mimalloc_rust hand writted sys binding"
license = "MIT"
# mimalloc version
version = "1.7.3-source"
edition = "2018"

[dependencies]
cty = "0.2"

[build-dependencies]
cc = "1.0"
